create extension if not exists pgcrypto;
create table if not exists public.resumes(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,template text not null default 'Standard',target_role text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.resume_versions(id uuid primary key default gen_random_uuid(),resume_id uuid not null references public.resumes(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,label text not null,template text not null default 'Standard',target_role text not null default '',sections jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.applications(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,company text not null,role text not null,location text not null default '',status text not null default 'saved' check(status in ('saved','applied','screening','interview','offer','rejected')),job_url text,notes text,resume_version_id uuid references public.resume_versions(id) on delete set null,updated_at timestamptz not null default now());
alter table public.resumes enable row level security;
alter table public.resume_versions enable row level security;
alter table public.applications enable row level security;
create policy "resume owner select" on public.resumes for select to authenticated using ((select auth.uid())=user_id);
create policy "resume owner insert" on public.resumes for insert to authenticated with check ((select auth.uid())=user_id);
create policy "resume owner update" on public.resumes for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "resume owner delete" on public.resumes for delete to authenticated using ((select auth.uid())=user_id);
create policy "version owner select" on public.resume_versions for select to authenticated using ((select auth.uid())=user_id);
create policy "version owner insert" on public.resume_versions for insert to authenticated with check ((select auth.uid())=user_id);
create policy "version owner update" on public.resume_versions for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "version owner delete" on public.resume_versions for delete to authenticated using ((select auth.uid())=user_id);
create policy "application owner select" on public.applications for select to authenticated using ((select auth.uid())=user_id);
create policy "application owner insert" on public.applications for insert to authenticated with check ((select auth.uid())=user_id);
create policy "application owner update" on public.applications for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "application owner delete" on public.applications for delete to authenticated using ((select auth.uid())=user_id);
create index if not exists resumes_user_updated on public.resumes(user_id,updated_at desc);
create index if not exists resume_versions_resume_created on public.resume_versions(resume_id,created_at desc);
create index if not exists applications_user_updated on public.applications(user_id,updated_at desc);