'use client'
import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { AlertTriangle, CheckCircle2, CirclePause, Play, RotateCcw, ShieldCheck, Square, TimerReset } from 'lucide-react'
import { ADAPTERS, adapterFor, handoffLabel, nextState, policyFor, type AutomationMode, type AutomationState } from '@/lib/automation-engine'
import { loadAutomationQueue, loadPreparationJob, saveAutomationQueue, uid, type RovaAutomationRecord } from '@/lib/storage'

const states: AutomationState[]=['queued','preparing','ready','running','human-review','submitted','verified','failed','cancelled']
const label=(s:string)=>s.replaceAll('-', ' ').replace(/\b\w/g,x=>x.toUpperCase())

export default function Automation(){
 const [mode,setMode]=useState<AutomationMode>('review'); const [queue,setQueue]=useState<RovaAutomationRecord[]>([]); const [paused,setPaused]=useState(false); const [notice,setNotice]=useState('')
 useEffect(()=>{setQueue(loadAutomationQueue())},[])
 const policy=useMemo(()=>policyFor(mode),[mode])
 function persist(next:RovaAutomationRecord[]){setQueue(next);saveAutomationQueue(next)}
 function enqueue(){const job=loadPreparationJob<any>();if(!job){setNotice('Prepare an application first.');return}const url=String(job.applyUrl||job.url||'');const adapter=adapterFor(url);const now=new Date().toISOString();const record:RovaAutomationRecord={id:uid('auto'),company:job.company||'Unknown company',role:job.title||'Selected role',source:job.source||'Unknown source',applicationUrl:url,state:'queued',attempts:0,maxAttempts:3,createdAt:now,updatedAt:now};persist([record,...queue]);setNotice(adapter?`${adapter.label} adapter selected.`:'No execution adapter selected; human review required.')}
 function advance(id:string,event:'prepare'|'start'|'pause'|'handoff'|'resume'|'submit'|'verify'|'fail'|'cancel'){persist(queue.map(j=>j.id===id?{...j,state:nextState(j.state as AutomationState,event),attempts:event==='start'?j.attempts+1:j.attempts,updatedAt:new Date().toISOString()}:j))}
 function retry(j:RovaAutomationRecord){if(j.attempts>=j.maxAttempts){setNotice('Retry limit reached.');return}advance(j.id,'prepare')}
 function clear(){persist([]);setNotice('Queue cleared.')}
 const counts=states.reduce((m,s)=>(m[s]=queue.filter(j=>j.state===s).length,m),{} as Record<string,number>)
 return <main className="main standalone"><Link className="back" href="/">← Command</Link><div className="mono eyebrow">ROVA / AUTOMATION ENGINE</div><div className="careerHead"><div><h1 className="title">Automate the repetitive. Keep the consequences visible.</h1><p className="lead">The control plane queues prepared applications, selects a platform adapter and pauses when confidence is insufficient. Browser execution remains a separate worker boundary.</p></div><div className="targetBox"><ShieldCheck size={16}/><div><span>Execution policy</span><strong>{label(mode)}</strong></div></div></div>
 <section className="careerStats"><div className="card"><div className="mono">QUEUE</div><div className="metric">{queue.length}</div><div className="sub">prepared execution jobs</div></div><div className="card"><div className="mono">HUMAN HANDOFF</div><div className="metric">{counts['human-review']||0}</div><div className="sub">awaiting explicit intervention</div></div><div className="card"><div className="mono">VERIFIED</div><div className="metric">{counts.verified||0}</div><div className="sub">submission state confirmed</div></div></section>
 <section className="section card"><div className="sectionhead"><h3>Permission boundary</h3><span className="mono">NO SILENT SUBMISSION</span></div><div className="tabs">{(['dry-run','review','full-auto'] as AutomationMode[]).map(x=><button key={x} className={mode===x?'selected':''} onClick={()=>setMode(x)}>{label(x)}</button>)}</div><div className="chips"><span className="chip">CAPTCHA pauses</span><span className="chip">Unknown forms pause</span><span className="chip">Sensitive questions pause</span><span className="chip">Verification required</span></div><p className="small">Policy is explicit. The Vercel control plane never claims a submission occurred merely because navigation succeeded.</p></section>
 <section className="section"><div className="sectionhead"><h3>Execution queue</h3><div><button className="ghost" onClick={()=>setPaused(!paused)}>{paused?<Play size={14}/>:<CirclePause size={14}/>} {paused?'Resume':'Pause'} queue</button> <button className="primary" onClick={enqueue}><Play size={14}/> Queue prepared application</button></div></div>{!queue.length?<div className="emptyPanel"><div className="emptyIcon"><TimerReset size={22}/></div><div><div className="mono">QUEUE EMPTY</div><h2>Prepare a role, then queue it.</h2><p>Application Preparation produces the evidence package. Automation consumes that package and does not invent missing candidate facts.</p><Link className="primary" href="/opportunities">Find a role</Link></div></div>:<div className="jobList">{queue.map(j=><article className="job intelligenceJob" key={j.id}><div className="jobtop"><div><div className="company">{j.company} · {j.source}</div><h4>{j.role}</h4><div className="small">Attempt {j.attempts}/{j.maxAttempts} · {j.applicationUrl||'No application URL'}</div></div><span className="badge">{label(j.state)}</span></div>{j.handoff&&<div className="warning"><AlertTriangle size={13}/> {handoffLabel(j.handoff as any)}</div>}{j.lastError&&<div className="warning">{j.lastError}</div>}<div className="jobfoot"><span className="mono">{paused?'QUEUE PAUSED':`MODE · ${label(mode)} · SUBMIT ${policy.allowExternalSubmission?'ENABLED':'BLOCKED'}`}</span><div className="jobActions">{j.state==='queued'&&<button className="link" onClick={()=>advance(j.id,'prepare')}><Play size={13}/> Prepare</button>}{(j.state==='ready'||j.state==='paused')&&<button className="link" onClick={()=>advance(j.id,'start')}><Play size={13}/> Start</button>}{j.state==='running'&&<><button className="link" onClick={()=>advance(j.id,'pause')}><CirclePause size={13}/> Pause</button><button className="link" onClick={()=>advance(j.id,'handoff')}><AlertTriangle size={13}/> Handoff</button></>}{j.state==='human-review'&&<button className="link" onClick={()=>advance(j.id,'resume')}><Play size={13}/> Resume</button>}{j.state==='submitted'&&<button className="link" onClick={()=>advance(j.id,'verify')}><CheckCircle2 size={13}/> Verify</button>}{j.state==='failed'&&<button className="link" onClick={()=>retry(j)}><RotateCcw size={13}/> Retry</button>}{!['verified','cancelled'].includes(j.state)&&<button className="link" onClick={()=>advance(j.id,'cancel')}><Square size={13}/> Cancel</button>}</div></div></article>)}</div>}</section>
 <section className="section"><div className="sectionhead"><h3>Platform adapters</h3><span className="mono">CONTRACTS / {ADAPTERS.length}</span></div><div className="careerRoles">{ADAPTERS.map(a=><article className="card careerRole" key={a.id}><div className="roleLine"><div><div className="mono">{a.kind}</div><h3>{a.label}</h3></div><span className="badge">{a.capabilities.length} capabilities</span></div><div className="chips">{a.capabilities.map(c=><span className="chip" key={c}>{c}</span>)}</div></article>)}</div></section>
 <div className="footer">Automation state is explicit and auditable. Browser sessions, credentials and site-specific execution belong in the separate worker/runtime, not in the Vercel request lifecycle. {notice}</div><button className="link" onClick={clear} style={{marginTop:10}}>Clear local queue</button></main>
}
