'use client'
import { useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Check } from 'lucide-react'
import { defaultProfile, saveProfile, type RovaProfile } from '@/lib/storage'
import { BRAND } from '@/lib/brand'
import { Surface, SectionHeader, Status } from '@/components/kindleap-ui'
type EditableField=Exclude<keyof RovaProfile,'targetRoles'|'skills'>
export default function OnboardingPage(){const[step,setStep]=useState(1);const[p,setP]=useState<RovaProfile>(defaultProfile);const update=(k:EditableField,v:string)=>setP(x=>({...x,[k]:v}));const updateList=(k:'targetRoles'|'skills',v:string)=>setP(x=>({...x,[k]:v.split(',').map(x=>x.trim()).filter(Boolean)}));function finish(){saveProfile(p);setStep(3)}return <main className="kl-public"><div className="kl-public-head"><Link href="/" className="kl-brand"><span className="kl-mark">K</span><span><b>{BRAND.name}</b><small>{BRAND.tagline}</small></span></Link><Status tone="accent">SETUP · 0{step===3?2:step}</Status></div><div className="kl-public-page">{step<3?<><SectionHeader eyebrow={`${BRAND.name} / Setup`} title={step===1?'Start with the facts.':'Set the direction.'} description={step===1?'KINDLEAP needs a small set of verified candidate facts before it can reason about roles.':'These targets shape role matching. They are preferences, not promises.'}/><Surface><div className="kl-form-grid">{step===1?<><Field label="Full name" value={p.name} onChange={v=>update('name',v)}/><Field label="Headline" value={p.headline} onChange={v=>update('headline',v)}/><Field label="Location" value={p.location} onChange={v=>update('location',v)}/></>:<><Field label="Target roles" value={p.targetRoles.join(', ')} onChange={v=>updateList('targetRoles',v)}/><Field label="Target salary" value={p.targetSalary} onChange={v=>update('targetSalary',v)} placeholder="e.g. ₹12 LPA"/><Field label="Skills" value={p.skills.join(', ')} onChange={v=>updateList('skills',v)}/></>}<div><button className="kl-button kl-button-primary" onClick={()=>step===1?setStep(2):finish()}>{step===1?'Continue':'Finish setup'} {step===1?<ArrowRight size={15}/>:<Check size={15}/>}</button></div></div></Surface></>:<Surface><Status tone="good">READY</Status><h2 className="kl-ready-title">Workspace ready.</h2><p>Your profile is saved locally in this prototype. Import a resume next and run the first intelligence check.</p><Link className="kl-button kl-button-primary" href="/resume">Open resume intelligence <ArrowRight size={15}/></Link></Surface>}</div></main>}
function Field({label,value,onChange,placeholder='' }:{label:string,value:string,onChange:(v:string)=>void,placeholder?:string}){return <label className="kl-field"><span>{label}</span><input value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
