import { NextResponse } from 'next/server'
import { supabaseForAccessToken } from '@/lib/supabase-server'
export const runtime='nodejs'
const ALLOWED=['prepared','review','applied','verified','rejected','withdrawn'] as const
function token(req:Request){const v=req.headers.get('authorization')||'';return v.startsWith('Bearer ')?v.slice(7):''}
async function auth(req:Request){const c=supabaseForAccessToken(token(req));if(!c)return null;const{data:{user}}=await c.auth.getUser();return user?{c,user}:null}
export async function GET(req:Request){const x=await auth(req);if(!x)return NextResponse.json({error:'Authentication is required.'},{status:401});const limit=Math.min(Number(new URL(req.url).searchParams.get('limit')||200),500);const{data,error}=await x.c.from('applications').select('*').order('updated_at',{ascending:false}).limit(limit);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({applications:data||[]})}
export async function POST(req:Request){const x=await auth(req);if(!x)return NextResponse.json({error:'Authentication is required.'},{status:401});try{const b=await req.json();if(!b?.jobKey||!b?.jobSnapshot||!b?.packageSnapshot)return NextResponse.json({error:'jobKey, jobSnapshot and packageSnapshot are required.'},{status:400});const snapshot=JSON.stringify(b.packageSnapshot);if(snapshot.length>200000)return NextResponse.json({error:'Application package is too large.'},{status:413});const row={user_id:x.user.id,job_key:String(b.jobKey).slice(0,500),job_snapshot:b.jobSnapshot,package_snapshot:b.packageSnapshot,status:'prepared',notes:String(b.notes||'').slice(0,5000)};const{data,error}=await x.c.from('applications').upsert(row,{onConflict:'user_id,job_key'}).select('*').single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({application:data},{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Invalid request.'},{status:400})}}
export async function PATCH(req:Request){const x=await auth(req);if(!x)return NextResponse.json({error:'Authentication is required.'},{status:401});try{const b=await req.json();const id=String(b?.id||'');const status=String(b?.status||'');if(!id||!(ALLOWED as readonly string[]).includes(status))return NextResponse.json({error:'Valid application id and status are required.'},{status:400});const patch:{status:string;notes?:string;applied_at?:string;verified_at?:string}={status};if(typeof b.notes==='string')patch.notes=b.notes.slice(0,5000);if(status==='applied')patch.applied_at=new Date().toISOString();if(status==='verified')patch.verified_at=new Date().toISOString();const{data,error}=await x.c.from('applications').update(patch).eq('id',id).select('*').single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({application:data})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Invalid request.'},{status:400})}}
