import { NextResponse } from 'next/server'
import { supabaseForAccessToken } from '@/lib/supabase-server'
import { canonicalJobKey, type JobRecord } from '@/lib/job-engine'
export const runtime='nodejs'
function token(req:Request){const v=req.headers.get('authorization')||'';return v.startsWith('Bearer ')?v.slice(7):''}
async function client(req:Request){const c=supabaseForAccessToken(token(req));if(!c)return null;const{data:{user}}=await c.auth.getUser();return user?{c,user}:null}
export async function GET(req:Request){const x=await client(req);if(!x)return NextResponse.json({error:'Authentication is required.'},{status:401});const{data,error}=await x.c.from('saved_roles').select('*').order('saved_at',{ascending:false}).limit(500);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({roles:data||[]})}
export async function POST(req:Request){const x=await client(req);if(!x)return NextResponse.json({error:'Authentication is required.'},{status:401});try{const b=await req.json();const job=b?.job as JobRecord;if(!job?.company||!job?.title||!job?.url)return NextResponse.json({error:'A complete job record is required.'},{status:400});const jobKey=canonicalJobKey(job);const{data,error}=await x.c.from('saved_roles').upsert({user_id:x.user.id,job_key:jobKey,job_snapshot:job,saved_at:new Date().toISOString()},{onConflict:'user_id,job_key'}).select('*').single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({role:data},{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Invalid request.'},{status:400})}}
export async function DELETE(req:Request){const x=await client(req);if(!x)return NextResponse.json({error:'Authentication is required.'},{status:401});const key=new URL(req.url).searchParams.get('jobKey')||'';if(!key)return NextResponse.json({error:'jobKey is required.'},{status:400});const{error}=await x.c.from('saved_roles').delete().eq('job_key',key);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true})}
