'use client'
import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowRight, BriefcaseBusiness, Check, ChevronRight, Target, TrendingUp } from 'lucide-react'
import { assessCareer } from '@/lib/career-engine'
import { defaultProfile, loadProfile, loadResumes, type RovaProfile } from '@/lib/storage'

export default function CareerPage(){
 const [profile,setProfile]=useState<RovaProfile>(defaultProfile); const [resume,setResume]=useState('')
 useEffect(()=>{setProfile(loadProfile());setResume(loadResumes()[0]?.content||'')},[])
 const [target,setTarget]=useState('')
 const effective={...profile,targetSalary:target||profile.targetSalary}
 const assessment=useMemo(()=>assessCareer(effective,resume),[effective,resume])
 return <main className="main standalone careerPage"><Link className="back" href="/">← Command</Link><div className="mono eyebrow">WAYO / CAREER LAB</div><div className="careerHead"><div><h1 className="title">Know where the profile can go.</h1><p className="lead">WAYO maps visible evidence to adjacent roles, career paths and a salary target. This is a planning model, not a promise of market compensation.</p></div><div className="targetBox"><Target size={16}/><label><span>Salary target</span><input value={target||profile.targetSalary} onChange={e=>setTarget(e.target.value)} placeholder="₹12 LPA"/></label></div></div>
 <section className="careerStats"><div className="card"><div className="mono">PROFILE SIGNAL</div><div className="metric">{assessment.currentSignal}</div><div className="sub">relative evidence strength</div></div><div className="card"><div className="mono">TARGET ASSESSMENT</div><div className="metric">{assessment.target.verdict==='within-range'?'ON RANGE':assessment.target.verdict==='stretch'?'STRETCH':'REBUILD'}</div><div className="sub">{assessment.target.headline}</div></div><div className="card"><div className="mono">BEST FIT</div><div className="metric">{assessment.recommended[0]?.fit||0}</div><div className="sub">{assessment.recommended[0]?.title||'Add profile evidence'}</div></div></section>
 <section className="section"><div className="sectionhead"><h3>Recommended roles</h3><span className="mono">PROFILE → ROLE FIT</span></div><div className="careerRoles">{assessment.recommended.map(r=><article className="card careerRole" key={r.title}><div className="roleLine"><div><div className="mono">{r.family}</div><h3>{r.title}</h3></div><div className="fit">{r.fit}</div></div><p>{r.rationale}</p><div className="salary">Planning band · ₹{r.salaryBand[0]}–₹{r.salaryBand[1]} LPA</div><div className="analysisBlock"><b>Already visible</b><div className="chips">{r.matched.slice(0,6).map(x=><span className="chip" key={x}>{x}</span>)}</div></div><div className="analysisBlock"><b>Build next</b><div className="chips">{r.gaps.slice(0,4).map(x=><span className="chip mutedChip" key={x}>{x}</span>)}</div></div></article>)}</div></section>
 <section className="section"><div className="sectionhead"><h3>Salary target analysis</h3><span className="mono">DECISION SUPPORT</span></div><div className="card targetPanel"><div><div className="mono">{assessment.target.verdict.toUpperCase()}</div><h2>{assessment.target.headline}</h2><div className="targetActions">{assessment.target.actions.map(x=><div key={x}><Check size={14}/><span>{x}</span></div>)}</div></div><div className="targetVisual"><TrendingUp size={21}/><strong>{assessment.targetLpa?`₹${assessment.targetLpa} LPA`:'Set a target'}</strong><span>planning target</span></div></div></section>
 <section className="section"><div className="sectionhead"><h3>Career paths</h3><span className="mono">NEXT 12–24 MONTHS</span></div><div className="pathGrid">{assessment.paths.map(p=><article className="card path" key={p.title}><BriefcaseBusiness size={17}/><h3>{p.title}</h3><div className="pathDirection">{p.direction}</div><div className="steps">{p.steps.map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span>{s}<ChevronRight size={13}/></div>)}</div></article>)}</div></section>
 <section className="section card nextStep"><div><div className="mono">NEXT STEP</div><h3>Turn the strongest path into applications.</h3><p>Use the recommended role and skill gaps to drive job search, resume tailoring and application preparation.</p></div><Link className="primary" href="/resume">Open resume intelligence <ArrowRight size={14}/></Link></section>
 <div className="footer">Planning salary bands are deterministic product heuristics until a live market-data source is connected.</div></main>
}
