'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Check, Clipboard, Copy, Save, ShieldCheck, WandSparkles } from 'lucide-react'
import { buildApplicationPack, type ApplicationPack } from '@/lib/application-engine'
import { canonicalJobKey, type JobRecord } from '@/lib/job-engine'
import { loadPreparationJob, loadProfile, loadResumes } from '@/lib/storage'
import { supabase } from '@/lib/supabase'
import { BRAND } from '@/lib/brand'
import { KindleapShell, SectionHeader, Signal, Status, Surface } from '@/components/kindleap-ui'
const statuses=['prepared','review','applied','verified','rejected','withdrawn'] as const
export default function Applications(){const[job,setJob]=useState<JobRecord|null>(null);const[pack,setPack]=useState<ApplicationPack|null>(null);const[copied,setCopied]=useState('');const[saving,setSaving]=useState(false);const[saved,setSaved]=useState(false);const[applicationId,setApplicationId]=useState('');const[status,setStatus]=useState<(typeof statuses)[number]>('prepared');const[message,setMessage]=useState('')
useEffect(()=>{const selected=loadPreparationJob<JobRecord>();setJob(selected);if(selected)setPack(buildApplicationPack(selected,loadProfile(),loadResumes()[0]||null))},[])
async function token(){if(!supabase)return '';const{data}=await supabase.auth.getSession();return data.session?.access_token||''}
async function saveApplication(){if(!job||!pack)return;setSaving(true);setMessage('');try{const access=await token();if(!access){setSaved(true);setMessage('Sign in to persist this application across devices.');return}const r=await fetch('/api/applications',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${access}`},body:JSON.stringify({jobKey:canonicalJobKey(job),jobSnapshot:job,packageSnapshot:pack})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save application');setApplicationId(d.application.id);setStatus(d.application.status);setSaved(true);setMessage('Application package saved privately.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save application.')}finally{setSaving(false)}}
async function changeStatus(next:string){if(!applicationId){setStatus(next as typeof status);setMessage('Save the application first to persist its status.');return}const access=await token();if(!access)return;setSaving(true);try{const r=await fetch('/api/applications',{method:'PATCH',headers:{'content-type':'application/json',authorization:`Bearer ${access}`},body:JSON.stringify({id:applicationId,status:next})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to update status');setStatus(d.application.status)}catch(e){setMessage(e instanceof Error?e.message:'Unable to update status.')}finally{setSaving(false)}}
function copy(label:string,text:string){navigator.clipboard?.writeText(text);setCopied(label);window.setTimeout(()=>setCopied(''),1200)}
if(!job||!pack)return <KindleapShell><div className="kl-page"><SectionHeader eyebrow="Application studio" title="Prepare with evidence." description="Select a role from Opportunities first. NAUKRI LABS builds a role-specific preparation pack from stored profile and resume evidence."/><Surface><Status>No role selected</Status><h2>Start with an opportunity.</h2><p>Choose a role before building an application package.</p><Link className="kl-button kl-button-primary" href="/opportunities"><WandSparkles size={14}/> Find a role</Link></Surface></div></KindleapShell>
return <KindleapShell><div className="kl-page"><SectionHeader eyebrow={`${BRAND.name} / Application studio`} title={pack.targetRole} description={`${job.company} · ${job.location||'Location unspecified'} · ${job.workMode||'Work mode unspecified'}`} action={<Signal label="Signal readiness" value={<>{pack.atsScore}<small>/100</small></>} detail="Evidence-bound heuristic"/>}/><div className="kl-package-grid"><Surface><div className="kl-eyebrow">RESUME VARIANT</div><h3>{pack.resumeVariant}</h3><p>{pack.summary}</p><div className="kl-chips">{pack.matched.map(x=><span key={x}>{x}</span>)}</div>{pack.missing.length>0&&<div className="kl-warning">Missing evidence: {pack.missing.join(', ')}. Do not add unsupported claims.</div>}</Surface><Surface><div className="kl-eyebrow">APPLICATION STATUS</div><select value={status} disabled={saving} onChange={e=>changeStatus(e.target.value)}>{statuses.map(x=><option key={x} value={x}>{x}</option>)}</select><div className="kl-form-foot"><button className="kl-button kl-button-primary" onClick={saveApplication} disabled={saving}><Save size={14}/>{saving?'Saving…':saved?'Saved':'Save application'}</button></div>{message&&<div className="kl-notice"><Check size={14}/>{message}</div>}</Surface></div><Surface><div className="kl-eyebrow">SAFETY CHECK</div><div className="kl-check-list">{pack.warnings.length?pack.warnings.map(x=><div key={x}><ShieldCheck size={14}/>{x}</div>):<div><ShieldCheck size={14}/>No unsupported claims detected in the generated package.</div>}</div><p className="kl-muted">Generated copy is constrained to available candidate evidence. Submission remains a separate controlled stage.</p></Surface><section className="kl-stack"><Surface><div className="kl-section-line"><div><div className="kl-eyebrow">COVER LETTER</div><h2>Role-specific draft</h2></div><button className="kl-button" onClick={()=>copy('cover',pack.coverLetter)}><Copy size={14}/>{copied==='cover'?'Copied':'Copy'}</button></div><pre className="kl-copy-block">{pack.coverLetter}</pre></Surface>{pack.answers.map((x,i)=><Surface key={x.question}><div className="kl-section-line"><div><div className="kl-eyebrow">ANSWER {String(i+1).padStart(2,'0')}</div><h3>{x.question}</h3></div><button className="kl-button" onClick={()=>copy(`a${i}`,x.answer)}><Clipboard size={14}/>{copied===`a${i}`?'Copied':'Copy'}</button></div><p>{x.answer}</p></Surface>)}</section><Link className="kl-back-link" href="/opportunities"><ArrowLeft size={14}/> Back to Opportunities</Link></div></KindleapShell>}
