'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { Check, LockKeyhole, Sparkles } from 'lucide-react'
import { supabase, isSupabaseConfigured } from '@/lib/supabase'
import { DEMO_EMAIL, DEMO_PASSWORD, redeemInviteCode } from '@/lib/entitlements'
import './auth.css'

export default function AuthPage(){
 const [mode,setMode]=useState<'sign-in'|'sign-up'>('sign-in'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [invite,setInvite]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false)
 useEffect(()=>{const params=new URLSearchParams(window.location.search);if(params.get('mode')==='sign-up')setMode('sign-up')},[])
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{
  if(email.trim().toLowerCase()===DEMO_EMAIL && password===DEMO_PASSWORD){localStorage.setItem('rova.demo.email',DEMO_EMAIL);localStorage.setItem('wayo.proAccess','true');setMessage('Test account active. Full Pro beta access unlocked.');return}
  if(mode==='sign-up' && invite.trim() && !redeemInviteCode(invite)){setMessage('That invite code is not valid.');return}
  if(!supabase){localStorage.setItem('rova.demo.email',email);if(mode==='sign-up'&&invite.trim())redeemInviteCode(invite);setMessage(mode==='sign-up'?'Account ready.':'Demo account ready.');return}
  const result=mode==='sign-in'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password})
  if(result.error) throw result.error
  if(mode==='sign-up'&&invite.trim())redeemInviteCode(invite)
  setMessage(mode==='sign-in'?'Signed in. Return to Command.':'Account created. Check your email if confirmation is enabled.')
 }catch(err){setMessage(err instanceof Error?err.message:'Authentication failed.')}finally{setBusy(false)}}
 return <main className="authPage"><Link className="authLogo" href="/"><span>W</span> WAYO</Link><div className="authShell"><section className="authIntro"><div className="mono">CAREER INTELLIGENCE / BETA</div><h1>The career workspace that stays in your hands.</h1><p>Basic tools stay open. Create an account only when you need the full Pro workspace, automation and persistent career intelligence.</p><div className="authPerks"><div><Check size={14}/> Resume + career intelligence</div><div><Check size={14}/> Job intelligence + application studio</div><div><Check size={14}/> Full Pro beta access with invite</div></div></section><section className="authCard"><div className="tabs"><button className={mode==='sign-in'?'selected':''} onClick={()=>setMode('sign-in')}>Sign in</button><button className={mode==='sign-up'?'selected':''} onClick={()=>setMode('sign-up')}>Create account</button></div><div className="authCardHead"><div className="authLock"><LockKeyhole size={16}/></div><div><div className="mono">{mode==='sign-up'?'FREE ACCOUNT':'WELCOME BACK'}</div><h2>{mode==='sign-up'?'Start free. Unlock more when ready.':'Continue your workspace.'}</h2></div></div><form onSubmit={submit}><label className="field"><span>Email</span><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label className="field"><span>Password</span><input type="password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder="8+ characters"/></label>{mode==='sign-up'&&<label className="field"><span>Beta invite code <small>optional</small></span><input value={invite} onChange={e=>setInvite(e.target.value)} placeholder="WAYO-BETA" autoCapitalize="characters"/><small className="small">Have a code? Enter it to unlock every Pro feature free during beta.</small></label>}<button className="primary authSubmit" type="submit" disabled={busy}>{busy?'Working…':mode==='sign-in'?'Sign in':'Create free account'} <Sparkles size={14}/></button></form>{message&&<div className="notice">{message}</div>}<div className="testBox"><div><b>Test access</b><span>For product review</span></div><code>{DEMO_EMAIL}</code><code>{DEMO_PASSWORD}</code></div><p className="small">{isSupabaseConfigured?'Secure Supabase authentication is active.':'Demo mode is active until Supabase project keys are configured.'}</p></section></div><footer>WAYO · Your career, in motion.</footer></main>}
