"use client";

import Link from "next/link";
import { ArrowRight, Check, ChevronDown, FileText, Search, Sparkles, Target, Wand2 } from "lucide-react";

const templates=["Standard","Modern","Creative","Classic","Balanced","Minimalist","Professional","Corporate","Bold","Slate","Executive","Insight"];
const features=[
  ["01","Resume Analysis","Score your resume across ATS structure, keywords, evidence, readability and role fit.","/workspace?view=analysis"],
  ["02","Resume Tailoring","Paste a job description and adapt the right sections without rewriting your whole career.","/workspace?view=tailor"],
  ["03","AI Resume Agent","Ask for help on a section, bullet or summary. Review each suggestion before it changes anything.","/workspace?view=agent"],
  ["04","ATS Templates","Choose from a large library of clean, recruiter-readable resume layouts.","/workspace?view=templates"],
  ["05","Cover Letter","Generate a focused letter from the same resume and role context.","/workspace?view=cover"],
  ["06","Job Search","Find roles, understand your match and keep applications attached to their documents.","/workspace?view=jobs"],
];

function Header(){return <header className="siteHeader"><Link href="/" className="logo">VEYRA<span>AI</span></Link><nav><Link href="#features">Features</Link><Link href="#templates">Templates</Link><Link href="#how">How it works</Link><Link href="#faq">FAQ</Link><Link href="/pricing">Pricing</Link></nav><div className="headerRight"><Link href="/workspace">Log in</Link><Link className="primary small" href="/workspace">Get started <ArrowRight size={14}/></Link></div></header>}

function ResumePreview(){return <div className="resumeStage"><div className="resumeWindow"><div className="windowTop"><span/><span/><span/><b>Resume</b><em>•••</em></div><div className="resumeCanvas"><div className="resumePaper"><div className="resumeName">Charles Bloomberg</div><div className="resumeMeta">Product Manager · Seoul, South Korea · charles@email.com · +61 799 5548</div><hr/><h5>PROFESSIONAL SUMMARY</h5><p>Product manager and startup operator with experience turning customer insight into measurable product and workflow improvements.</p><h5>PROFESSIONAL EXPERIENCE</h5><b>Founder — Rezi</b><small>Aug 2015 — Present · Seoul, South Korea</small><ul><li>Built structured workflows that improved resume clarity and application quality.</li><li>Led product experiments across onboarding and lifecycle workflows.</li><li>Partnered with engineering and growth to ship measurable improvements.</li></ul><b>Web Developer — Kaplan</b><small>Mar 2014 — May 2015 · La Crosse, WI</small><ul><li>Built analytics and reporting workflows across acquisition channels.</li><li>Improved landing-page content paths for conversion-focused campaigns.</li></ul><h5>EDUCATION</h5><p>University of Wisconsin — Madison · B.A. Economics</p></div><aside className="agentPreview"><div className="agentHead"><span><Sparkles size={13}/> Veyra Agent</span><i>×</i></div><div className="agentScore"><strong>78</strong><span>/100<br/>resume score</span></div><div className="agentSuggestion"><b>Strengthen this bullet</b><p>Lead with the outcome, then add scale or measurable evidence.</p><button>Apply suggestion</button></div><div className="agentSuggestion muted"><b>Keyword gap</b><p>“Roadmap” appears in the role but not in your experience.</p></div></aside></div></div></div>}

function FAQ(){const items=[["What is Veyra?","Veyra is an AI career workspace for building, analyzing and tailoring resumes, creating cover letters and organizing applications."],["Can I upload an existing resume?","Yes. The first flow supports importing an existing resume or starting from a blank document."],["Does the AI change my resume automatically?","No. Suggestions are presented as reviewable edits. You decide what gets applied."],["Do I need a job description?","No. You can build and analyze a base resume first. A job description is used for role-specific analysis and tailoring."],["Can I export a PDF?","Yes. The workspace is designed around a print-ready resume and PDF export."],["How many templates are there?","The reference product exposes 34 ATS-oriented templates. Veyra starts with a comparable template library and a consistent rendering system."]];return <section id="faq" className="section faq"><div><label>FAQ</label><h2>Everything you need<br/><i>before you apply.</i></h2></div><div>{items.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={17}/></summary><p>{a}</p></details>)}</div></section>}

export default function Home(){return <><Header/><main><section className="hero section"><div className="heroCopy"><div className="eyebrowPill"><Sparkles size={13}/> AI-powered resume workspace</div><h1>Stop getting ignored.<br/><i>Start getting noticed.</i></h1><p>Build a stronger resume, understand exactly what is holding it back, then tailor it to every role you actually want.</p><div className="heroActions"><Link className="primary" href="/workspace">Build my resume <ArrowRight size={16}/></Link><Link className="underLink" href="#how">See how it works <ArrowRight size={14}/></Link></div><div className="microTrust"><span><Check size={13}/> Free to start</span><span><Check size={13}/> No credit card</span><span><Check size={13}/> ATS-ready templates</span></div></div><div className="heroVisual"><ResumePreview/></div></section>

<section className="proofStrip"><div><b>01</b><span>Build or import</span></div><div><b>02</b><span>Analyze what is missing</span></div><div><b>03</b><span>Tailor to the role</span></div><div><b>04</b><span>Apply with confidence</span></div></section>

<section className="section problem"><label>THE PROBLEM</label><h2>Most resumes do not fail<br/><i>because the experience is bad.</i></h2><p className="lede">They fail because the relevant evidence is buried, the language does not map to the role, or the document asks the recruiter to do too much work.</p><div className="problemGrid">{[["ATS rejection","The document does not surface the terms and structure screening systems expect."],["Missing keywords","Relevant skills exist in your experience but never appear where they matter."],["Weak evidence","Responsibilities are listed without outcomes, scale or proof."],["Too generic","One unchanged resume is used for fundamentally different jobs."]].map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>

<section id="features" className="section featureSection"><label>THE WORKSPACE</label><h2>Everything between<br/><i>resume and application.</i></h2><div className="featureGrid">{features.map(([n,t,d,u])=><Link href={u} className="featureCard" key={n}><div><span>{n}</span><Wand2 size={18}/></div><h3>{t}</h3><p>{d}</p><span className="featureLink">Open workspace <ArrowRight size={13}/></span></Link>)}</div></section>

<section id="how" className="darkSection"><div className="darkInner"><div><label>HOW IT WORKS</label><h2>One source resume.<br/><i>Many precise applications.</i></h2><p>Keep your underlying experience intact. Change emphasis, terminology and ordering only where the job calls for it.</p><Link className="lightButton" href="/workspace">Start building <ArrowRight size={15}/></Link></div><div className="flow"><article><b>01</b><div><strong>Create</strong><p>Import your existing resume or choose a template and build from scratch.</p></div></article><article><b>02</b><div><strong>Analyze</strong><p>Get a score and section-level fixes for structure, keywords and impact.</p></div></article><article><b>03</b><div><strong>Tailor</strong><p>Paste the job description and review role-specific edits before applying.</p></div></article></div></div></section>

<section id="templates" className="section templates"><label>34 ATS-FRIENDLY TEMPLATES</label><h2>Pick the structure.<br/><i>Keep the content yours.</i></h2><div className="templateRail">{templates.map((t,i)=><div className="templateCard" key={t}><div className={"templatePaper t"+i}><strong>CHARLES BLOOMBERG</strong><span>PRODUCT MANAGER</span><hr/><i/><i/><i/><i/><hr/><i/><i/><i/></div><b>{t}</b></div>)}</div><Link className="underLink" href="/workspace?view=templates">View the full library <ArrowRight size={14}/></Link></section>

<section className="outcomes"><div className="outcomeInner"><div><label>BUILT FOR THE JOB HUNT</label><h2>The goal is not a prettier resume.<br/><i>It is a more relevant one.</i></h2></div><div className="outcomeCards"><article><strong>48 → 82</strong><span>Resume score after targeted fixes</span></article><article><strong>12</strong><span>Matched role signals surfaced from one job description</span></article><article><strong>1 → ∞</strong><span>Source resume adapted across applications</span></article></div></div></section>

<section className="section cta"><div className="eyebrowPill">Start with what you already have</div><h2>Build the resume<br/><i>the job actually needs.</i></h2><Link className="primary" href="/workspace">Create my resume <ArrowRight size={16}/></Link></section><FAQ/></main><footer className="footer"><div><Link href="/" className="logo">VEYRA<span>AI</span></Link><p>An independent AI career workspace.</p></div><div><b>Product</b><Link href="/workspace">Resume Builder</Link><Link href="/workspace?view=analysis">Analysis</Link><Link href="/workspace?view=tailor">Tailoring</Link><Link href="/workspace?view=jobs">Job Search</Link></div><div><b>Company</b><Link href="/pricing">Pricing</Link><Link href="/workspace">Sign in</Link></div><small>Independent implementation based on publicly observable product patterns. Not affiliated with Jobsuit AI.</small></footer></>}