'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowRight, RefreshCw } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import { supabase } from '@/lib/supabase'
import { KindleapShell, SectionHeader, Signal, Surface } from '@/components/kindleap-ui'
export default function Insights(){const[apps,setApps]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('')
useEffect(()=>{(async()=>{try{if(!supabase){setLoading(false);return}const{data}=await supabase.auth.getSession();const access=data.session?.access_token;if(!access){setLoading(false);return}const r=await fetch('/api/applications',{headers:{authorization:`Bearer ${access}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load applications');setApps(d.applications||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load applications.')}finally{setLoading(false)}})()},[])
const counts=apps.reduce((a,x)=>{a.total++;a[x.status]=(a[x.status]||0)+1;return a},{total:0} as Record<string,number>);const applied=(counts.applied||0)+(counts.verified||0);const verified=counts.verified||0
return <KindleapShell><div className="kl-page"><SectionHeader eyebrow={`${BRAND.name} / Outcomes`} title="Measure the search." description="These are personal application records, not market statistics." action={<Signal label="Applications" value={String(counts.total||0)} detail="Durable records"/>}/>{loading?<Surface><p>Loading application history…</p></Surface>:error?<Surface><p className="kl-warning">{error}</p></Surface>:!apps.length?<Surface><h2>No applications recorded yet.</h2><p>Prepare and save an application to start building a private outcome history.</p><Link className="kl-button kl-button-primary" href="/opportunities">Find a role <ArrowRight size={14}/></Link></Surface>:<><div className="kl-signal-grid"><Signal label="Prepared" value={counts.prepared||0}/><Signal label="In review" value={counts.review||0}/><Signal label="Applied" value={applied}/><Signal label="Verified" value={verified}/></div><Surface><h2>Current history</h2><p>{applied?`${applied} application${applied===1?'':'s'} marked applied or verified.`:'No applications have been marked applied yet.'} {verified?`${verified} verified submission${verified===1?'':'s'}.`:'Independent submission verification is not yet available.'}</p><Link className="kl-button" href="/applications">Open application studio <RefreshCw size={14}/></Link></Surface></>}</div></KindleapShell>}
