'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { FileText, Trash2, Upload, ShieldCheck, ArrowLeft } from 'lucide-react'
import { loadDocuments, saveDocuments, uid, type RovaDocument } from '@/lib/storage'
import { supabase } from '@/lib/supabase'
import { BRAND } from '@/lib/brand'
import { KindleapShell, SectionHeader, Signal, Surface, Status } from '@/components/kindleap-ui'
export default function DocumentsPage(){
 const [docs,setDocs]=useState<RovaDocument[]>([]);const[busy,setBusy]=useState(false);const[status,setStatus]=useState('');useEffect(()=>setDocs(loadDocuments()),[])
 async function add(e:React.ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files||[]);if(!files.length)return;setBusy(true);setStatus('');let message='';const next=[...docs];for(const f of files){let text='';try{if(f.type==='text/plain'||f.name.endsWith('.md'))text=await f.text()}catch{}let storagePath:string|undefined;if(supabase){const {data:{user}}=await supabase.auth.getUser();if(user){storagePath=`${user.id}/${uid('file')}_${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const upload=await supabase.storage.from('documents').upload(storagePath,f,{upsert:false});if(upload.error){message=upload.error.message;continue}const row=await supabase.from('documents').insert({user_id:user.id,name:f.name,storage_path:storagePath,mime_type:f.type||'',size_bytes:f.size,extracted_text:text});if(row.error){await supabase.storage.from('documents').remove([storagePath]);message=row.error.message;continue}}}next.unshift({id:uid('doc'),name:f.name,type:f.type||'file',size:f.size,uploadedAt:new Date().toISOString(),extractedText:text,storagePath})}setDocs(next);saveDocuments(next);setBusy(false);setStatus(message||`Added ${files.length} document${files.length===1?'':'s'}.`);e.target.value=''}
 async function remove(id:string){const doc=docs.find(d=>d.id===id);if(!doc)return;setBusy(true);setStatus('');if(supabase&&doc.storagePath){const {data:{user}}=await supabase.auth.getUser();if(user&&doc.storagePath.startsWith(`${user.id}/`)){const storage=await supabase.storage.from('documents').remove([doc.storagePath]);if(storage.error){setStatus(storage.error.message);setBusy(false);return}const row=await supabase.from('documents').delete().eq('user_id',user.id).eq('storage_path',doc.storagePath);if(row.error){setStatus(row.error.message);setBusy(false);return}}}const next=docs.filter(d=>d.id!==id);setDocs(next);saveDocuments(next);setBusy(false);setStatus('Document removed.')} 
 return <KindleapShell><div className="kl-page"><SectionHeader eyebrow={`${BRAND.name} / Source library`} title="Keep the evidence close." description="Store the documents KINDLEAP can use as source material. Private cloud storage is used when Supabase is configured." action={<Signal label="Library" value={docs.length} detail="source documents"/>}/><Surface><div className="kl-upload"><div><Upload size={18}/><b>{busy?'Working…':'Add source documents'}</b><p>PDF, DOCX, TXT and Markdown. Files remain the source; generated claims do not become evidence automatically.</p></div><label className="kl-button kl-button-primary"><Upload size={14}/> Choose files<input type="file" multiple accept=".pdf,.docx,.txt,.md" onChange={add}/></label></div>{status&&<div className="kl-notice"><ShieldCheck size={14}/>{status}</div>}{!docs.length?<div className="kl-empty"><FileText size={22}/><div><Status>No documents</Status><h3>Start with your current resume.</h3><p>Your source library will become the evidence layer for later intelligence.</p></div></div>:<div className="kl-doc-list">{docs.map(d=><div className="kl-doc-row" key={d.id}><FileText size={18}/><div><b>{d.name}</b><small>{Math.round(d.size/1024)} KB · {new Date(d.uploadedAt).toLocaleDateString()}</small></div><button className="kl-icon-button" onClick={()=>remove(d.id)} disabled={busy} aria-label={`Delete ${d.name}`}><Trash2 size={15}/></button></div>)}</div>}</Surface><Link className="kl-back-link" href="/workspace"><ArrowLeft size={14}/> Back to Command</Link></div></KindleapShell>}
