'use client'
import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { Bookmark, ExternalLink, Filter, Loader2, Search, Target, Upload, X, WandSparkles } from 'lucide-react'
import { analyseJob, canonicalJobKey, type JobRecord } from '@/lib/job-engine'
import { defaultProfile, loadProfile, loadSavedRoles, savePreparationJob, saveSavedRoles, type RovaProfile } from '@/lib/storage'

const seed: JobRecord[] = [
 {id:'demo-linear',company:'Linear',title:'Product Designer',location:'Remote',workMode:'Remote',employment:'Full-time',source:'Demo source',url:'https://linear.app/careers',applyUrl:'https://linear.app/careers',description:'Build product experiences, design systems and workflows for a modern B2B SaaS product. Partner with engineers and product managers. Strong Figma, interaction design, prototyping and product thinking.',salary:'',department:'Design'},
 {id:'demo-vercel',company:'Vercel',title:'Senior Product Designer',location:'Remote',workMode:'Remote',employment:'Full-time',source:'Demo source',url:'https://vercel.com/careers',applyUrl:'https://vercel.com/careers',description:'Lead product design for developer tools. Work across systems, interaction design, prototyping, research and technical collaboration with product and engineering.',salary:'',department:'Design'},
 {id:'demo-notion',company:'Notion',title:'Product Designer, Growth',location:'New York',workMode:'Hybrid',employment:'Full-time',source:'Demo source',url:'https://www.notion.com/careers',applyUrl:'https://www.notion.com/careers',description:'Design growth experiences, experimentation and user journeys. Partner with product, research and engineering. Strong product design and experimentation skills.',salary:'',department:'Growth'}
]
function mergeUnique(current:JobRecord[], incoming:JobRecord[]) { const seen=new Set<string>(); const result:JobRecord[]=[]; for(const job of [...incoming,...current]) { const key=canonicalJobKey(job); if(!seen.has(key)){seen.add(key);result.push(job)} } return result }

export default function Opportunities(){
 const [profile,setProfile]=useState<RovaProfile>(defaultProfile); const [jobs,setJobs]=useState(seed); const [q,setQ]=useState(''); const [source,setSource]=useState(''); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [selected,setSelected]=useState<JobRecord|null>(null); const [saved,setSaved]=useState<string[]>([])
 useEffect(()=>{setProfile(loadProfile());setSaved(loadSavedRoles().map(x=>x.id))},[])
 const analyses=useMemo(()=>new Map(jobs.map(j=>[j.id,analyseJob(j,profile)])),[jobs,profile])
 const filtered=useMemo(()=>jobs.filter(j=>`${j.company} ${j.title} ${j.location} ${j.description}`.toLowerCase().includes(q.toLowerCase())),[jobs,q])
 async function loadSource(){setError('');if(!source.trim()){setError('Paste a public Greenhouse, Lever or Ashby board or individual job URL.');return}setLoading(true);try{const r=await fetch('/api/job-source',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:source})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Source failed');setJobs(prev=>mergeUnique(prev,data.jobs||[]));setSource('')}catch(e){setError(e instanceof Error?e.message:'Unable to load source.')}finally{setLoading(false)}}
 function toggleSave(id:string){const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);saveSavedRoles(next.map(x=>({id:x,savedAt:new Date().toISOString()})))}
 function prepare(job:JobRecord){savePreparationJob(job);window.location.href='/applications'}
 return <main className="main standalone"><Link className="back" href="/">← Command</Link><div className="mono eyebrow">ROVA / JOB INTELLIGENCE</div><div className="careerHead"><div><h1 className="title">Search the market with context.</h1><p className="lead">Aggregate public ATS job boards, scan individual job URLs, score roles against the candidate profile and keep provenance attached to every opportunity.</p></div><div className="targetBox"><Target size={16}/><div><span>Free public sources</span><strong>Greenhouse · Lever · Ashby</strong></div></div></div>
 <section className="formcard sourceCard"><div className="mono">SCAN A PUBLIC JOB SOURCE</div><div className="sourceRow"><input value={source} onChange={e=>setSource(e.target.value)} placeholder="Board URL or individual job URL"/><button className="primary" onClick={loadSource} disabled={loading}>{loading?<Loader2 className="spin" size={15}/>:<Upload size={15}/>} {loading?'Scanning…':'Scan'}</button></div><div className="small">Board URLs load published roles. Individual Greenhouse, Lever and Ashby job URLs are resolved where the public source exposes them.</div>{error&&<div className="warning">{error}</div>}</section>
 <section className="section"><div className="toolbar"><div className="searchInline"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search roles, companies, skills…"/></div><div className="mono"><Filter size={12}/> {filtered.length} roles · {saved.length} saved</div></div><div className="jobList">{filtered.map(j=>{const a=analyses.get(j.id)!;const duplicateCount=jobs.filter(x=>analyses.get(x.id)?.duplicateKey===a.duplicateKey).length;return <article className="job intelligenceJob" key={j.id}><div className="jobtop"><div><div className="company">{j.company} · {j.source}</div><h4>{j.title}</h4><div className="small">{j.location || 'Location unspecified'} · {j.workMode || 'Work mode unspecified'} · {j.employment || 'Employment unspecified'}</div></div><div className="score">{a.fit}</div></div><div className="chips"><span className="chip">{j.salary||'Compensation undisclosed'}</span>{j.department&&<span className="chip">{j.department}</span>}<span className="chip">{a.seniority}</span>{duplicateCount>1&&<span className="chip mutedChip">Duplicate source</span>}</div><p className="jobsummary">{a.summary}</p><div className="jobfoot"><button className="link" onClick={()=>setSelected(j)}>Inspect intelligence →</button><div className="jobActions"><button className="link" onClick={()=>prepare(j)}><WandSparkles size={14}/>Prepare</button><button className="link" onClick={()=>toggleSave(j.id)}><Bookmark size={14} fill={saved.includes(j.id)?'currentColor':'none'}/>{saved.includes(j.id)?'Saved':'Save'}</button><a className="link" href={j.applyUrl||j.url} target="_blank" rel="noreferrer">Source <ExternalLink size={13}/></a></div></div></article>})}</div></section>
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="detailPanel" onClick={e=>e.stopPropagation()}><div className="detailHead"><div><div className="mono">{selected.company} · {selected.source}</div><h2>{selected.title}</h2><p>{selected.location} · {selected.workMode}</p></div><button className="link" onClick={()=>setSelected(null)}><X size={18}/></button></div><JobDetail job={selected} profile={profile} prepare={prepare}/></div></div>}
 <div className="footer">Public ATS feeds are used where available. ROVA does not claim company facts, salary or career relevance that the source does not expose.</div></main>
}
function JobDetail({job,profile,prepare}:{job:JobRecord,profile:RovaProfile,prepare:(job:JobRecord)=>void}){const a=analyseJob(job,profile);return <div className="detailBody"><div className="detailScore"><div><span>FIT</span><strong>{a.fit}</strong><small>/100</small></div><div>{a.signals.map(s=><div className="signal" key={s.label}><span>{s.label}</span><b>{s.value}</b></div>)}</div></div><div className="analysisBlock"><b>Career relevance</b><p>{a.careerRelevance}</p></div><div className="analysisBlock"><b>Company / team context</b><p>{a.companyContext}</p></div><div className="analysisBlock"><b>Project signals</b><div className="chips">{a.projectSignals.length?a.projectSignals.map(x=><span className="chip" key={x}>{x}</span>):<span className="small">No project signals extracted.</span>}</div></div><div className="analysisBlock"><b>Why it fits</b><p>{a.summary}</p></div><div className="analysisBlock"><b>Matched evidence</b><div className="chips">{a.matched.length?a.matched.map(x=><span className="chip" key={x}>{x}</span>):<span className="small">No direct evidence detected.</span>}</div></div><div className="analysisBlock"><b>Missing signal</b><div className="chips">{a.gaps.map(x=><span className="chip mutedChip" key={x}>{x}</span>)}</div></div><div className="analysisBlock"><b>Role description</b><p className="description">{job.description||'No description supplied by the source.'}</p></div><div className="jobActions"><button className="primary" onClick={()=>prepare(job)}>Prepare application <WandSparkles size={14}/></button><a className="primary" href={job.applyUrl||job.url} target="_blank" rel="noreferrer">Open source / application <ExternalLink size={14}/></a></div></div>}
