import Link from 'next/link'
import { ArrowUpRight, Check, LockKeyhole, Sparkles } from 'lucide-react'
import { BRAND } from '@/lib/brand'
import '../growth/growth.css'
import './pricing.css'

const plans = [
  { name: 'Free', price: '₹0', note: 'Start with the signal layer. No account required for basic tools.', features: ['Basic resume audit', 'Job discovery + saved roles', 'Basic fit signals', 'Public job-post scanning'], cta: 'Explore free', href: '/opportunities' },
  { name: 'Pro', price: '₹499', note: 'The complete career intelligence and controlled execution layer.', features: ['Everything in Free', 'Resume Studio + deep analysis', 'Career Lab + salary planning', 'Application Studio', 'Interview + Outcome Lab', 'Controlled automation + tracking', 'Advanced intelligence layers'], cta: 'Unlock Pro', href: '/auth?mode=sign-up' },
]

export default function Pricing(){return <main className="growthPage"><header className="growthHeader"><Link href="/" className="growthLogo"><span>K</span>{BRAND.name}</Link><div><b>ACCESS / 11</b><i>ENTITLEMENTS</i></div><nav><Link href="/growth">Growth</Link><Link href="/community">Community</Link><Link href="/auth">Sign in</Link></nav></header><section className="growthHero"><span className="growthIndex">ACCESS / 001</span><div><p>MONETISATION</p><h1>Pay for leverage.<br/><em>Not for permission.</em></h1><span className="growthLead">KINDLEAP keeps the basic signal layer open. Pro unlocks deeper intelligence, execution and automation without turning the product into a credit meter.</span></div><div className="goalStamp"><Sparkles size={20}/><b>BETA</b><strong>Invite = Pro</strong><span>Full Pro access during the beta with a valid invite.</span></div></section><section className="goalEditor"><div className="growthIndex">A / 01</div><div><p>CHOOSE YOUR LAYER</p><h2>One system.<br/><em>Two levels of depth.</em></h2></div><div className="goalFields">{plans.map(p=><article key={p.name} className="pricePlan"><header><div><small>{p.name.toUpperCase()}</small><strong>{p.price}<i>/month</i></strong></div>{p.name==='Pro'&&<b>BETA</b>}</header><span>{p.note}</span><div>{p.features.map(f=><label key={f}><Check size={13}/>{f}</label>)}</div><Link href={p.href}>{p.cta}<ArrowUpRight size={14}/></Link></article>)}</div></section><section className="weeklyPlan"><div className="growthIndex">B / 02</div><div><p>ACCESS MODEL</p><h2>Simple enough<br/><em>to trust.</em></h2></div><div className="accessRules"><div><LockKeyhole/><b>Account-bound Pro</b><span>Entitlements belong to the authenticated account, not a fragile client-side switch.</span></div><div><Check/><b>Beta invitation</b><span>A valid beta invite can unlock the complete Pro workspace during the beta period.</span></div><div><Sparkles/><b>Credits later</b><span>Usage credits remain an optional future entitlement layer, never the core product.</span></div></div></section><footer><span>{BRAND.name} · {BRAND.tagline}</span><span>Access with control</span></footer></main>}
