'use client'
import { useMemo, useState } from 'react'
import Link from 'next/link'
import { FileText, ScanSearch, Sparkles } from 'lucide-react'
import { analyzeResume, extractResumeText } from '@/lib/resume-engine'
import { loadProfile } from '@/lib/storage'

const sampleRole=`Product Designer. Build and evolve design systems for a B2B SaaS product. Partner with product managers and engineers. Strong Figma, prototyping, UX research, interaction design, experimentation and accessibility skills. 3+ years experience.`
export default function ResumePage(){
 const [resume,setResume]=useState(''); const [role,setRole]=useState(sampleRole); const [busy,setBusy]=useState(false); const [name,setName]=useState('Resume'); const profile=useMemo(()=>loadProfile(),[]); const analysis=useMemo(()=>analyzeResume(resume,role),[resume,role])
 async function file(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setName(f.name.replace(/\.[^.]+$/,''));setBusy(true);try{if(f.type==='text/plain'||f.name.endsWith('.md'))setResume(extractResumeText(await f.text()));else if(f.name.endsWith('.docx')){const mammoth=await import('mammoth');const r=await mammoth.extractRawText({arrayBuffer:await f.arrayBuffer()});setResume(extractResumeText(r.value))}else if(f.type==='application/pdf'||f.name.endsWith('.pdf')){const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');const pdf=await pdfjs.getDocument({data:new Uint8Array(await f.arrayBuffer()),disableWorker:true}).promise;let out='';for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i);const c=await p.getTextContent();out+=c.items.map((x:any)=>x.str).join(' ')+'\n'}setResume(extractResumeText(out))}else setResume(await f.text())}catch{setResume('Unable to parse this file in the current browser session. Paste the resume text below.')}finally{setBusy(false)}}
 return <main className="main standalone"><Link className="back" href="/">← Command</Link><div className="mono eyebrow">ROVA / RESUME INTELLIGENCE</div><h1 className="title">Make the resume legible to the market.</h1><p className="lead">Import a resume, compare it against a target role, and see the evidence behind the score.</p><section className="resumeGrid"><div className="formcard"><div className="upload"><FileText size={22}/><div><b>{busy?'Parsing…':'Import resume'}</b><small>PDF, DOCX, TXT or Markdown</small></div><input type="file" accept=".pdf,.docx,.txt,.md" onChange={file}/></div><label className="field"><span>Resume content · {name}</span><textarea value={resume} onChange={e=>setResume(e.target.value)} placeholder="Paste your resume text here…" rows={18}/></label><label className="field"><span>Target job description</span><textarea value={role} onChange={e=>setRole(e.target.value)} rows={8}/></label></div><div className="analysis card"><div className="mono">ATS / FIT CHECK</div><div className="bigscore">{analysis.score}<small>/100</small></div><p>{analysis.summary}</p><div className="analysisBlock"><b>Detected sections</b><div className="chips">{analysis.sections.map(x=><span className="chip" key={x}>{x}</span>)}</div></div><div className="analysisBlock"><b>Matched terms</b><div className="chips">{analysis.matchedSkills.slice(0,14).map(x=><span className="chip" key={x}>{x}</span>)}</div></div><div className="analysisBlock"><b>Missing signal</b><div className="chips">{analysis.missingSkills.map(x=><span className="chip mutedChip" key={x}>{x}</span>)}</div></div><div className="analysisBlock"><b>Checks</b>{analysis.warnings.length?analysis.warnings.map(x=><div className="warning" key={x}>• {x}</div>):<div className="ok">No structural warnings detected.</div>}</div><button className="primary"><Sparkles size={15}/> Build targeted version</button></div></section><section className="section card"><div className="review"><div><div className="mono">Profile context</div><h3>{profile.name || 'Candidate'} · {profile.targetSalary || 'Target salary not set'}</h3><p>{profile.skills.length?profile.skills.join(' · '):'Add skills in your profile so ROVA can compare candidate evidence against roles.'}</p></div><ScanSearch size={25}/></div></section></main>
}
