'use client'
import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Check, Download, FileText, Sparkles, Upload } from 'lucide-react'
import { analyzeResume, extractResumeText } from '@/lib/resume-engine'
import { defaultProfile, loadProfile, loadResumes, saveResumes, uid, type RovaProfile } from '@/lib/storage'
import { supabase } from '@/lib/supabase'
import './resume.css'

export default function ResumePage(){
 const [resume,setResume]=useState('');const[role,setRole]=useState('');const[name,setName]=useState('My Resume');const[profile,setProfile]=useState<RovaProfile>(defaultProfile);const[busy,setBusy]=useState(false);const[saved,setSaved]=useState(false)
 useEffect(()=>{setProfile(loadProfile());const x=loadResumes()[0];if(x){setResume(x.content);setRole(x.targetRole);setName(x.name)}},[])
 const analysis=useMemo(()=>analyzeResume(resume,role),[resume,role])
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setBusy(true);setName(f.name.replace(/\.[^.]+$/,''));try{if(f.type==='text/plain'||f.name.endsWith('.md'))setResume(extractResumeText(await f.text()));else if(f.name.endsWith('.docx')){const m=await import('mammoth');const x=await m.extractRawText({arrayBuffer:await f.arrayBuffer()});setResume(extractResumeText(x.value))}else if(f.name.endsWith('.pdf')){const p=await import('pdfjs-dist/legacy/build/pdf.mjs');const pdf=await(p.getDocument as any)({data:new Uint8Array(await f.arrayBuffer()),disableWorker:true}).promise;let out='';for(let i=1;i<=pdf.numPages;i++){const pg=await pdf.getPage(i);const c=await pg.getTextContent();out+=c.items.map((x:any)=>x.str).join(' ')+'\n'}setResume(extractResumeText(out))}else setResume(await f.text())}finally{setBusy(false)}}
 async function save(){const record={id:uid('resume'),name,content:resume,targetRole:role,atsScore:analysis.score,updatedAt:new Date().toISOString()};saveResumes([record,...loadResumes().filter(x=>x.name!==name)]);setSaved(true);if(supabase){const{data:{user}}=await supabase.auth.getUser();if(user)await supabase.from('resumes').insert({user_id:user.id,name,content:resume,target_role:role,ats_score:analysis.score})}setTimeout(()=>setSaved(false),1600)}
 return <main className="jr-page"><header className="jr-nav"><Link href="/" className="jr-logo">JOBSUIT <span>AI</span></Link><nav><Link href="/resume">Resume Builder</Link><Link href="/assistant">Tailor</Link><Link href="/career">Analysis</Link><Link href="/pricing">Pricing</Link></nav><Link href="/auth" className="jr-login">Log in</Link></header>
 <section className="jr-head"><div><span className="jr-pill">AI resume builder</span><h1>Build a resume<br/><em>that gets read.</em></h1><p>Create or import your resume, check it against a target role, and refine the content in one focused workspace.</p></div><div className="jr-head-actions"><label className="jr-upload"><Upload size={15}/> {busy?'Importing…':'Upload resume'}<input type="file" accept=".pdf,.docx,.txt,.md" onChange={upload}/></label><button onClick={save} className="jr-dark"><Check size={15}/>{saved?'Saved':'Save resume'}</button></div></section>
 <section className="jr-workspace"><div className="jr-editor"><div className="jr-editor-top"><div><b>{name}</b><small>Editable source</small></div><input value={name} onChange={e=>setName(e.target.value)} aria-label="Resume name"/></div><label><span>Target job title or description</span><input value={role} onChange={e=>setRole(e.target.value)} placeholder="e.g. Senior Product Designer — paste the job description for deeper analysis"/></label><label><span>Resume content</span><textarea value={resume} onChange={e=>setResume(e.target.value)} placeholder="Upload a resume or start writing here…" rows={30}/></label><button className="jr-dark" onClick={()=>window.print()}><Download size={15}/> Print / save PDF</button></div>
 <aside className="jr-side"><div className="jr-score"><span>RESUME SCORE</span><strong>{analysis.score}<small>/100</small></strong><div><i style={{width:Math.min(100,analysis.score)+'%'}}/></div><p>{analysis.summary}</p></div><Block title="SECTIONS" items={analysis.sections}/><Block title="MATCHED KEYWORDS" items={analysis.matchedSkills.slice(0,12)}/><Block title="MISSING SIGNALS" items={analysis.missingSkills.slice(0,10)} muted/><div className="jr-agent"><Sparkles size={16}/><div><b>Resume Agent</b><p>Use the tailor workspace to adapt this resume to a specific job.</p><Link href="/assistant">Tailor this resume <ArrowRight size={13}/></Link></div></div></aside></section>
 <footer className="jr-footer"><span>JOBSUIT AI</span><span>Build. Analyze. Tailor. Apply.</span></footer></main>
}
function Block({title,items,muted=false}:{title:string;items:string[];muted?:boolean}){return <section className="jr-block"><span>{title}</span><div>{items.length?items.map(x=><b className={muted?'muted':''} key={x}>{x}</b>):<small>None detected.</small>}</div></section>}
