'use client'
import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { FileText, Sparkles, Save, Download } from 'lucide-react'
import { analyzeResume, extractResumeText } from '@/lib/resume-engine'
import { defaultProfile, loadProfile, loadResumes, saveResumes, uid, type RovaProfile } from '@/lib/storage'
const sampleRole=`Product Designer. Build and evolve design systems for a B2B SaaS product. Partner with product managers and engineers. Strong Figma, prototyping, UX research, interaction design, experimentation and accessibility skills. 3+ years experience.`
export default function ResumePage(){
 const [tab,setTab]=useState<'intelligence'|'builder'>('intelligence'); const [resume,setResume]=useState(''); const [role,setRole]=useState(sampleRole); const [busy,setBusy]=useState(false); const [name,setName]=useState('Resume'); const [profile,setProfile]=useState<RovaProfile>(defaultProfile); const [saved,setSaved]=useState(false)
 useEffect(()=>{setProfile(loadProfile());const first=loadResumes()[0];if(first){setResume(first.content);setRole(first.targetRole);setName(first.name)}},[])
 const analysis=useMemo(()=>analyzeResume(resume,role),[resume,role])
 async function file(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setName(f.name.replace(/\.[^.]+$/,''));setBusy(true);try{if(f.type==='text/plain'||f.name.endsWith('.md'))setResume(extractResumeText(await f.text()));else if(f.name.endsWith('.docx')){const mammoth=await import('mammoth');const r=await mammoth.extractRawText({arrayBuffer:await f.arrayBuffer()});setResume(extractResumeText(r.value))}else if(f.type==='application/pdf'||f.name.endsWith('.pdf')){const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');const pdf=await (pdfjs.getDocument as any)({data:new Uint8Array(await f.arrayBuffer()),disableWorker:true}).promise;let out='';for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i);const c=await p.getTextContent();out+=c.items.map((x:any)=>x.str).join(' ')+'\n'}setResume(extractResumeText(out))}else setResume(await f.text())}catch{setResume('Unable to parse this file in the current browser session. Paste the resume text below.')}finally{setBusy(false)}}
 function save(){const all=loadResumes();const record={id:uid('resume'),name,content:resume,targetRole:role,atsScore:analysis.score,updatedAt:new Date().toISOString()};saveResumes([record,...all.filter(x=>x.name!==name)]);setSaved(true);setTimeout(()=>setSaved(false),1800)}
 return <main className="main standalone"><Link className="back" href="/">← Command</Link><div className="mono eyebrow">ROVA / RESUME INTELLIGENCE</div><h1 className="title">Make the resume legible to the market.</h1><p className="lead">Import a resume, extract its evidence, compare it against a target role, then shape a clean version without inventing candidate facts.</p><div className="tabs"><button className={tab==='intelligence'?'selected':''} onClick={()=>setTab('intelligence')}>Intelligence</button><button className={tab==='builder'?'selected':''} onClick={()=>setTab('builder')}>Resume builder</button></div>{tab==='intelligence'?<section className="resumeGrid"><div className="formcard"><div className="upload"><FileText size={22}/><div><b>{busy?'Parsing…':'Import resume'}</b><small>PDF, DOCX, TXT or Markdown</small></div><input type="file" accept=".pdf,.docx,.txt,.md" onChange={file}/></div><label className="field"><span>Resume content · {name}</span><textarea value={resume} onChange={e=>setResume(e.target.value)} placeholder="Paste your resume text here…" rows={18}/></label><label className="field"><span>Target job description</span><textarea value={role} onChange={e=>setRole(e.target.value)} rows={8}/></label><button className="primary" onClick={save}><Save size={15}/>{saved?'Saved':'Save resume version'}</button></div><div className="analysis card"><div className="mono">ATS / FIT CHECK</div><div className="bigscore">{analysis.score}<small>/100</small></div><p>{analysis.summary}</p><AnalysisBlock title="Detected sections" items={analysis.sections}/><AnalysisBlock title="Matched terms" items={analysis.matchedSkills.slice(0,14)}/><AnalysisBlock title="Missing signal" items={analysis.missingSkills} muted/><div className="analysisBlock"><b>Checks</b>{analysis.warnings.length?analysis.warnings.map(x=><div className="warning" key={x}>• {x}</div>):<div className="ok">No structural warnings detected.</div>}</div><button className="ghost" onClick={()=>setTab('builder')}><Sparkles size={15}/> Build targeted version</button></div></section>:<Builder profile={profile} resume={resume} setResume={setResume} />}</main>
}
function AnalysisBlock({title,items,muted=false}:{title:string,items:string[],muted?:boolean}){return <div className="analysisBlock"><b>{title}</b><div className="chips">{items.length?items.map(x=><span className={`chip ${muted?'mutedChip':''}`} key={x}>{x}</span>):<span className="small">None detected.</span>}</div></div>}
function Builder({profile,resume,setResume}:{profile:RovaProfile,resume:string,setResume:(v:string)=>void}){const generated=`${profile.name}\n${profile.headline}\n${profile.location} · ${profile.email} · ${profile.phone}\n\nSUMMARY\n${profile.headline || 'Add a concise professional summary based only on your verified experience.'}\n\nSKILLS\n${profile.skills.join(' · ') || 'Add verified skills in Profile.'}\n\nEXPERIENCE\n${resume.match(/(?:experience|work history)[\s\S]*/i)?.[0] || 'Paste or edit verified experience here.'}\n\nEDUCATION\n${resume.match(/education[\s\S]*/i)?.[0] || 'Add verified education here.'}`; const [value,setValue]=useState(resume||generated);return <section className="builderGrid"><div className="formcard"><div className="mono">EDITABLE SOURCE</div><textarea className="builderText" value={value} onChange={e=>{setValue(e.target.value);setResume(e.target.value)}} rows={30}/><button className="primary" onClick={()=>window.print()}><Download size={15}/> Print / save PDF</button></div><div className="card preview"><div className="mono">LIVE PREVIEW</div><pre>{value}</pre></div></section>}
