"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {Check,ChevronDown,ChevronRight,Download,FileText,LayoutGrid,MessageCircle,Plus,Search,Sparkles,Target,Upload,Briefcase,PenLine,BarChart3} from "lucide-react";

const sections=["Contact","Professional Summary","Experience","Education","Skills","Projects","Additional Information"];
const jobs=[["Product Manager","Atlassian","Sydney, Australia","91%"],["Senior Product Manager","Canva","Melbourne, Australia","87%"],["Product Lead","Airbnb","Remote","82%"],["Growth Product Manager","HubSpot","Boston, MA","78%"]];
const templates=["Standard","Modern","Creative","Classic","Balanced","Minimalist","Professional","Corporate","Bold","Slate","Executive","Insight","Atelier","Elegant","Aqua","Coastal","Vibrant","Meridian","Monarch","Verona","Onyx","Spark","Azure","Amber","Crimson","Cobalt","Jade","Signature","Heritage","Graphite","Skyline","Console","Horizon","Professional Compact"];

function ResumePaper({template="Standard"}:{template?:string}){return <div className={"workspacePaper template-"+template.replaceAll(" ","-")}><header><h1>Charles Bloomberg</h1><p>Product Manager · Seoul, South Korea · charles@email.com · +61 799 5548 · LinkedIn</p></header><section><h4>PROFESSIONAL SUMMARY</h4><p>Product manager and startup operator with a record of turning customer insight into measurable product and workflow improvements. Experienced across strategy, research, analytics and cross-functional execution.</p></section><section><h4>PROFESSIONAL EXPERIENCE</h4><h3>Founder — Rezi</h3><small>Aug 2015 — Present · Seoul, South Korea</small><ul><li>Built structured resume workflows that improved candidate clarity, keyword targeting and application quality.</li><li>Led product experiments across onboarding, lifecycle and application workflows.</li><li>Partnered with engineering and growth teams to ship measurable improvements.</li></ul><h3>Web Developer — Kaplan</h3><small>Mar 2014 — May 2015 · La Crosse, WI</small><ul><li>Built analytics and reporting workflows across acquisition channels.</li><li>Improved landing-page content paths for conversion-focused campaigns.</li></ul></section><section><h4>EDUCATION</h4><p><b>University of Wisconsin — Madison</b> · B.A. Economics</p></section><section><h4>SKILLS</h4><p>Product strategy · Analytics · SQL · Research · Workflow automation · Tableau · Google Analytics · HTML · CSS · Python</p></section></div>}

function Sidebar({view,setView}:{view:string,setView:(v:string)=>void}){const items=[["resume","Resume",""],["analysis","Resume analysis",""],["tailor","Tailor resume",""],["agent","AI Agent",""],["templates","Templates",""],["cover","Cover letter",""],["jobs","Job search",""]];return <aside className="appSidebar"><Link href="/" className="appLogo">VEYRA<span>AI</span></Link><button className="newResume"><Plus size={14}/> New resume</button><nav>{items.map(([id,label])=><button key={id} onClick={()=>setView(id)} className={view===id?"active":""}>{id==="resume"?<FileText size={15}/>:id==="analysis"?<BarChart3 size={15}/>:id==="tailor"?<Target size={15}/>:id==="agent"?<Sparkles size={15}/>:id==="templates"?<LayoutGrid size={15}/>:id==="cover"?<PenLine size={15}/>:<Briefcase size={15}/>}<span>{label}</span></button>)}</nav><div className="sidebarBottom"><button><MessageCircle size={14}/> Help</button><Link href="/pricing">Upgrade plan <ChevronRight size={13}/></Link></div></aside>}

function Editor({setView}:{setView:(v:string)=>void}){const [section,setSection]=useState(0);const [agent,setAgent]=useState(true);return <div className="editorView"><div className="editorTop"><div><b>Charles Bloomberg</b><span>Saved just now</span></div><div className="editorTopActions"><button onClick={()=>setView("templates")}><LayoutGrid size={14}/> Change template</button><button className="export"><Download size={14}/> Download PDF</button></div></div><div className="editorBody"><div className="sectionNav"><span>RESUME SECTIONS</span>{sections.map((s,i)=><button key={s} onClick={()=>setSection(i)} className={section===i?"active":""}><span>{i+1}</span>{s}<ChevronRight size={12}/></button>)}<button className="addSection"><Plus size={13}/> Add section</button></div><div className="resumeViewport"><ResumePaper/><div className="zoom"><button>−</button><span>85%</span><button>+</button></div></div>{agent&&<aside className="agentPanel"><div className="agentPanelHead"><div><Sparkles size={14}/> Veyra Agent</div><button onClick={()=>setAgent(false)}>×</button></div><div className="agentIntro"><b>Resume score</b><strong>78<span>/100</span></strong><div className="scoreBar"><i/></div><p>Good foundation. Three fixes can materially improve this resume.</p></div><div className="agentTabs"><button className="active">Suggestions</button><button>Chat</button></div><div className="suggestion"><span className="tag">EXPERIENCE</span><h4>Make the first bullet outcome-led</h4><p>“Built structured resume workflows…” is clear, but the impact is not quantified.</p><div className="suggestionExample"><small>Suggested direction</small><p>Lead with the measurable change first, then explain what you built.</p></div><div className="suggestionActions"><button className="apply"><Check size={13}/> Apply</button><button>Dismiss</button></div></div><div className="suggestion"><span className="tag">KEYWORD</span><h4>Roadmap is missing</h4><p>The target role mentions roadmap ownership. Add it only where your experience supports it.</p><div className="suggestionActions"><button>Ask AI</button><button>Dismiss</button></div></div><div className="agentPrompt"><input placeholder="Ask about this resume…"/><button><Sparkles size={14}/></button></div></aside>}</div></div>}

function Analysis(){return <div className="featureView"><div className="featureHeader"><span>RESUME ANALYSIS</span><h2>See where your resume stands.</h2><p>Each section is scored independently so you know what to fix and why.</p></div><div className="analysisGrid"><div className="scoreCard"><span>OVERALL SCORE</span><strong>78<small>/100</small></strong><div className="bigRing"><b>78</b></div><p>Good foundation. Your experience is clear; relevance and measurable impact are the biggest opportunities.</p></div><div className="analysisSections">{[["ATS structure","92","Strong","Your structure is readable and machine-friendly."],["Keyword alignment","76","Good","12 relevant signals found; 4 role terms are missing."],["Impact evidence","64","Improve","Several bullets describe responsibilities without outcomes."],["Readability","88","Strong","Clear hierarchy and concise section formatting."],["Role relevance","71","Good","The base resume is broad and can be tightened for a target role."]].map(x=><article key={x[0]}><div><b>{x[0]}</b><span>{x[2]}</span></div><div className="miniBar"><i style={{width:x[1]+"%"}}/></div><p>{x[3]}</p></article>)}</div></div></div>}

function Tailor(){const [done,setDone]=useState(false);return <div className="featureView"><div className="featureHeader"><span>RESUME TAILORING</span><h2>Tailor this resume to one role.</h2><p>Paste the job description. Veyra extracts requirements, finds gaps and prepares reviewable edits.</p></div><div className="tailorGrid"><section className="inputPanel"><div className="panelTitle"><b>Job description</b><span>Required</span></div><textarea defaultValue={"Senior Product Manager\n\nWe are looking for a product leader to own product strategy, roadmap, customer discovery and cross-functional execution. You will work closely with engineering, design and go-to-market teams to deliver measurable outcomes."}/><div className="pasteActions"><button><Upload size={14}/> Paste from clipboard</button><button onClick={()=>setDone(true)} className="primaryApp">Analyze role <ChevronRight size={14}/></button></div></section><section className="matchPanel"><div className="matchTop"><span>ROLE MATCH</span><strong>{done?"86":"84"}%</strong></div>{[["Product strategy","Strong evidence"],["Roadmap ownership","Partial evidence"],["Customer discovery","Strong evidence"],["Cross-functional execution","Strong evidence"],["Measurable outcomes","Needs attention"]].map((x,i)=><div className="matchRow" key={x[0]}><span className={i===4?"warn":"ok"}>{i===4?"!":"✓"}</span><div><b>{x[0]}</b><small>{x[1]}</small></div><ChevronRight size={13}/></div>)}<button className="primaryApp full" onClick={()=>setViewFromTailor()}>Review tailored edits</button></section></div></div>}

let setViewFromTailor=()=>{};

function Templates({setView}:{setView:(v:string)=>void}){const [selected,setSelected]=useState("Standard");return <div className="featureView"><div className="featureHeader"><span>RESUME TEMPLATES</span><h2>Choose a format that gets out of the way.</h2><p>34 layouts designed around ATS readability and recruiter scanning.</p></div><div className="templateGrid">{templates.map(t=><button key={t} onClick={()=>setSelected(t)} className={selected===t?"selected":""}><ResumePaper template={t}/><b>{t}</b><span>{selected===t?"Selected":"Use template"}</span></button>)}</div><button className="primaryApp" onClick={()=>setView("resume")}>Use {selected} <ChevronRight size={14}/></button></div>}

function Jobs(){return <div className="featureView"><div className="featureHeader"><span>AI JOB SEARCH</span><h2>Find roles you actually qualify for.</h2><p>Search across multiple job sources and understand why a role matches your resume.</p></div><div className="jobSearch"><Search size={16}/><input placeholder="Job title, skill or keyword" defaultValue="Product Manager"/><input placeholder="Location" defaultValue="Remote"/><button className="primaryApp">Search jobs</button></div><div className="jobsList">{jobs.map(j=><article key={j[1]}><div className="companyMark">{j[1][0]}</div><div><h3>{j[0]}</h3><b>{j[1]}</b><span>{j[2]}</span><p>Matched because of product strategy, analytics, roadmap and cross-functional experience.</p></div><strong>{j[3]}<small>match</small></strong><button>View role</button></article>)}</div></div>}

function Cover(){return <div className="featureView"><div className="featureHeader"><span>COVER LETTER</span><h2>One letter. Built from your actual story.</h2><p>Use your resume and target role together instead of starting from a blank page.</p></div><div className="coverGrid"><div className="coverForm"><label>Target company<input defaultValue="Atlassian"/></label><label>Role<input defaultValue="Senior Product Manager"/></label><label>What should the letter emphasize?<textarea defaultValue="Product strategy, customer discovery, cross-functional execution and measurable outcomes." /></label><button className="primaryApp">Generate draft <Sparkles size={14}/></button></div><div className="letter"><span>PREVIEW</span><h2>Dear Hiring Team,</h2><p>I’m excited to apply for the Senior Product Manager role at Atlassian. My experience sits at the intersection of product strategy, customer insight and cross-functional execution.</p><p>In previous roles, I’ve led product experiments, translated customer signals into workflow improvements and partnered closely with engineering and growth teams to ship measurable changes.</p><p>I’d welcome the opportunity to bring that operating style to your team.</p><p>Best,<br/>Charles Bloomberg</p></div></div></div>}

function Agent(){return <div className="featureView"><div className="featureHeader"><span>AI RESUME AGENT</span><h2>A career editor that asks before it rewrites.</h2><p>Work section by section. Keep control of every change.</p></div><div className="chat"><div className="chatMessages"><div className="msg ai"><Sparkles size={14}/><p>Which part of your resume should we improve first?</p></div><div className="quick"><button>Improve my summary</button><button>Strengthen my bullets</button><button>Find missing keywords</button><button>Check ATS structure</button></div><div className="msg user"><p>Strengthen my bullets, but don't invent metrics.</p></div><div className="msg ai"><Sparkles size={14}/><p>Understood. I’ll keep the underlying claims intact and focus on clearer outcomes, ownership and role-relevant language. I found 3 bullets worth reviewing.</p></div></div><div className="chatInput"><input placeholder="Ask the agent anything about your resume…"/><button><Sparkles size={14}/></button></div></div></div>}

export default function Workspace(){const params=typeof window!=="undefined"?new URLSearchParams(window.location.search):null;const initial=params?.get("view")||"resume";const [view,setView]=useState(initial);return <div className="workspaceApp"><Sidebar view={view} setView={setView}/><main className="workspaceMain">{view==="resume"&&<Editor setView={setView}/>} {view==="analysis"&&<Analysis/>} {view==="tailor"&&<Tailor/>} {view==="agent"&&<Agent/>} {view==="templates"&&<Templates setView={setView}/>} {view==="jobs"&&<Jobs/>} {view==="cover"&&<Cover/>}</main></div>}