import { NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase-server'

export const runtime = 'nodejs'

export async function POST(req: Request) {
  const expected=process.env.ROVA_WORKER_CALLBACK_TOKEN||''; if(!expected||req.headers.get('authorization')!==`Bearer ${expected}`)return NextResponse.json({error:'Unauthorized.'},{status:401})
  const admin=supabaseAdmin(); if(!admin)return NextResponse.json({error:'Server persistence is not configured.'},{status:503})
  try{const body=await req.json();if(!body?.jobId||!body?.workerTaskId||!body?.state)return NextResponse.json({error:'Invalid worker result.'},{status:400}); const {data:job,error:je}=await admin.from('automation_jobs').select('id,user_id,worker_task_id,attempts,max_attempts').eq('id',body.jobId).single();if(je||!job)return NextResponse.json({error:'Automation job not found.'},{status:404});if(job.worker_task_id&&job.worker_task_id!==body.workerTaskId)return NextResponse.json({error:'Worker task does not match job.'},{status:409})
    const stateMap:Record<string,string>={started:'running',navigating:'running',handoff:'human-review',ready:'ready',submitted:'submitted',verified:'verified',failed:'failed'};const nextState=stateMap[String(body.state)]||'failed';const retryable=nextState==='failed'&&job.attempts<job.max_attempts;const patch={state:retryable?'failed':nextState,worker_task_id:body.workerTaskId,worker_state:body.state,handoff:body.handoffReason||null,last_error:nextState==='failed'?String(body.message||'Worker execution failed.'):null,evidence:body.evidence||{},lease_owner:null,lease_expires_at:null,next_attempt_at:retryable?new Date(Date.now()+Math.min(300000,30000*Math.max(1,job.attempts))).toISOString():new Date().toISOString(),updated_at:new Date().toISOString()};const {error:ue}=await admin.from('automation_jobs').update(patch).eq('id',job.id);if(ue)return NextResponse.json({error:ue.message},{status:500});await admin.from('automation_events').insert({user_id:job.user_id,automation_job_id:job.id,event_type:`worker:${body.state}`,state:patch.state,message:String(body.message||''),metadata:{workerTaskId:body.workerTaskId,handoffReason:body.handoffReason||null,evidence:body.evidence||{},retryScheduled:retryable}});return NextResponse.json({ok:true,state:patch.state,retryScheduled:retryable})
  }catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Invalid callback.'},{status:400})}
}
